-- AlterTable
ALTER TABLE `File` ADD COLUMN `bucket` VARCHAR(191) NULL,
    ADD COLUMN `etag` VARCHAR(191) NULL,
    ADD COLUMN `key` VARCHAR(191) NULL,
    ADD COLUMN `location` VARCHAR(191) NULL,
    MODIFY `link` VARCHAR(191) NULL;
